# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SighUp',
            new_name='SignUp',
        ),
    ]
