# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 18:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20160519_1342'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
